
export const ACTION_TYPES = {
    GET_FILMS: 'GET_FILMS',
    CLICK_FILM: 'CLICK_FILM',
    SELECT_CATEGORY_FILMS: 'SELECT_CATEGORY_FILMS',
    SELECT_NAVIGATION_TYPY_FILMS: 'SELECT_NAVIGATION_TYPY_FILMS',

    INPUT_LOGIN: 'INPUT_LOGIN',
    INPUT_PASSWORD: 'INPUT_PASSWORD',
    INPUT_NAME: 'INPUT_NAME',
    GET_USER: 'GET_USER',

    CHANGE_RATING: 'CHANGE_RATING',

    SEARCH_INPUT: 'SEARCH_INPUT',
    GET_SEARCH_FILMS: 'GET_SEARCH_FILMS',
}