
export const ACTION_TYPES = {
    GET_FILMS: 'GET_FILMS',
    CLICK_FILM: 'CLICK_FILM',
    SELECT_CATEGORY_FILMS: 'SELECT_CATEGORY_FILMS',
    SELECT_NAVIGATION_TYPE_FILMS: 'SELECT_NAVIGATION_TYPE_FILMS',

    INPUT_EMAIL: 'INPUT_EMAIL',
    INPUT_PASSWORD: 'INPUT_PASSWORD',
    INPUT_LOGIN: 'INPUT_LOGIN',
    GET_USER: 'GET_USER',
    GET_ACCESSTOKEN_USER: 'GET_ACCESSTOKEN_USER',
    ERROR_REGISTER: 'ERROR_REGISTER',

    SEARCH_INPUT: 'SEARCH_INPUT',
    GET_SEARCH_FILMS: 'GET_SEARCH_FILMS',

    SELECT_VALUE_FILTER_COUNTRY: 'SELECT_VALUE_FILTER_COUNTRY',
    SELECT_VALUE_FILTER_YEAR: 'SELECT_VALUE_FILTER_YEAR',
    SELECT_VALUE_FILTER_STAR: 'SELECT_VALUE_FILTER_STAR',

    SAVE_FILM_USER: 'SAVE_FILM_USER',
}